import { BrainCircuit, GitBranch, ListChecks, Radio } from "lucide-react";
import { CandidateCard } from "../components/CandidateCard";
import { SiteHeader } from "../components/SiteHeader";
import { DEMO_CANDIDATE } from "../config/demoCandidate";
import type { InterviewError } from "../types/interview";

interface LandingPageProps {
  onStart: () => void;
  isStarting: boolean;
  error: InterviewError | null;
}

const VALUE_POINTS = [
  {
    icon: BrainCircuit,
    title: "AI-driven questioning",
    body: "Each question is generated by the interview agent based on your role and prior answers.",
  },
  {
    icon: GitBranch,
    title: "Adaptive interview flow",
    body: "The conversation branches depending on how you respond — there's no fixed script.",
  },
  {
    icon: ListChecks,
    title: "Structured evaluation",
    body: "Your answers are assessed by the backend before the next question is chosen.",
  },
  {
    icon: Radio,
    title: "Realistic interview pace",
    body: "One question at a time, in a focused workspace built for a real interview session.",
  },
];

export function LandingPage({ onStart, isStarting, error }: LandingPageProps) {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />

      <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col justify-center gap-14 px-6 py-14 sm:px-10 lg:flex-row lg:items-center lg:gap-20">
        <div className="max-w-xl animate-fade-up">
          <span className="font-mono text-[11px] uppercase tracking-[0.14em] text-accent">
            Adaptive technical interviews
          </span>
          <h1 className="mt-4 font-display text-[44px] leading-[1.08] tracking-tight sm:text-[54px]">
            An AI interviewer,
            <br />
            not a chatbot.
          </h1>
          <p className="mt-5 text-[17px] leading-relaxed text-ink-muted">
            Practice realistic technical interviews where each question is
            generated and evaluated through an AI-driven interview workflow —
            one focused question at a time.
          </p>

          <ul className="mt-10 space-y-5">
            {VALUE_POINTS.map(({ icon: Icon, title, body }) => (
              <li key={title} className="flex gap-3.5">
                <span className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-accent-soft text-accent-dark">
                  <Icon size={16} strokeWidth={2} aria-hidden="true" />
                </span>
                <div>
                  <p className="text-sm font-medium text-ink">{title}</p>
                  <p className="mt-0.5 text-sm leading-snug text-ink-muted">
                    {body}
                  </p>
                </div>
              </li>
            ))}
          </ul>
        </div>

        <div className="flex flex-col items-center gap-3 lg:items-start">
          <CandidateCard
            candidate={DEMO_CANDIDATE}
            onStart={onStart}
            disabled={isStarting}
            isStarting={isStarting}
          />
          {error && (
            <p role="alert" className="max-w-sm text-sm text-danger">
              {error.message}
            </p>
          )}
        </div>
      </main>
    </div>
  );
}
